farms/urls.py
from django.urls import path
from . import views 

app_name = "farms"

urlpatterns = [
    path('',views.HomeView.as_view(), name="home"),
    path('categories/',views.categories,name="categories"),
    path('crop/<slug:slug>/',views.detail, name="crop-detail"),
    path('about/',views.about_us,name="about"),
    path('services/',views.services,name="services"),
]

farms_database/urls.py
from django.contrib import admin
from django.urls import path, include

from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('farms.urls')),
]

# To display images
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

templates/base.html
{% load static %}
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <title>{% block metatitle %}ZAMBOANGA FARMS{% endblock metatitle %}</title>
    <meta name="description" content="">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="robots" content="all,follow">
    <link rel="stylesheet" href="{% static 'css/bootstrap.min.css' %}">
    <link rel="stylesheet" href="{% static 'css/aos.css' %}">
    <link rel="stylesheet" href="{% static 'css/style.css' %}">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.2.0/css/all.min.css" integrity="sha512-xh6O/CkQoPOWDdYTDqeRdPCVd1SpvCA9XXcUnZS2FmJNp1coAFzvtCN9BmamE+4aHK8yyUHUSCcJHgXloTyT2A==" crossorigin="anonymous" referrerpolicy="no-referrer" />
    <link rel="shortcut icon" href="{% static 'images/leaf.png' %}">
  </head>
  <body>
    <div class="page-holder">
        {% include 'navbar.html' %}
        {% block content %}
        {% endblock content %}
        {% include 'footer.html' %}
        <script src="{% static 'js/jquery.min.js' %}"></script>
        <script src="{% static 'js/bootstrap.min.js' %}"></script>
        <script src="{% static 'js/aos.js' %}"></script>
        <script src="{% static 'js/custom.js' %}"></script>
    </div>
  </body>
  </html>

templates/footer.html
{% load static %}
<footer class="footer-area bg-img">

    <div class="main-footer-area">
        <div class="container">
            <div class="row">

          
                <div class="col-12 col-sm-6 col-lg-3">
                    <div class="single-footer-widget">
                        <div class="footer-logo mb-30">
                            <a href="https://www.pagasa.dost.gov.ph/"><img src="{% static 'images/core-img/pagasa.png' %}" style="height:100px;" alt=""></a> &nbsp; &nbsp; &nbsp; &nbsp; &nbsp;
                            <a href="https://www.da.gov.ph/"><img src="{% static 'images/core-img/agriculture.png' %}" style="height:100px;" alt=""></a>
                        </div>
                        <p>In collaboration with the Department of Agriculture and DOST-PAGASA.</p>
                        
                    </div>
                </div>

      
          

                <div class="col-12 col-sm-6 col-lg-3">
                    <div class="single-footer-widget">
                        <div class="widget-title">
                            <h5>Quote</h5>
                        </div>

                        <div class="contact-information">
                           <p>The kind of soil in your area determines the type of crop you <br>will plant to harvest; The kind of potentials in you will decide the type of success you will celebrate.</p>
                        </div>
                        &nbsp;
                    </div>
                </div>

        
                

                <div class="col-12 col-sm-6 col-lg-20">
                    <div class="single-footer-widget">
                        <div class="widget-title">
                            <h5>CONTACT</h5>
                        </div>

                        <div class="contact-information">
                            <p>Western Mindanao State University, College of Computing Studies</p>
                            <p><span>Address:</span> Normal Road, Baliwasan, Zamboanga City, Philippines</p>
                            <p><span>Phone:</span> 777-867-5309</p>
                            <p><span>Email:</span> ics@wmsu.edu.ph</p>
                            <p><span>Open hours:</span> Mon - Sat: 8 AM to 5 PM</p>
                        </div>
                        &nbsp;
                    </div>
                </div>
            </div>
        </div>
    </div>

    

    <div class="footer-bottom-area">
        <div class="container">
<div id="ww_62d7c552bbbb5" v='1.20' loc='id' a='{"t":"responsive","lang":"en","ids":["wl1384"],"cl_bkg":"image","cl_font":"#FFFFFF","cl_cloud":"#FFFFFF","cl_persp":"#81D4FA","cl_sun":"#FFC107","cl_moon":"#FFC107","cl_thund":"#FF5722","sl_tof":"5","sl_sot":"celsius","sl_ics":"one_a","font":"Arial"}'>Weather Data Source: <a href="https://cuacalab.id/cuaca_zamboanga_city/hari_ini/" id="ww_62d7c552bbbb5_u" target="_blank">cuaca hari ini di Zamboanga City</a></div><script async src="https://srv1.weatherwidget.org/js/?id=ww_62d7c552bbbb5"></script>
            <div class="row">
                <div class="col-12">
                    <div class="border-line"></div>
                </div>
                <div class="col-12 col-md-6">
                    <div class="copywrite-text">
                        <p> <a target="_blank" href="https://django-template.empress997.repl.co/">Group 6 BSIT 4 - A</a></p>
                    </div>
                </div>
               
            </div>
        </div>
    </div>
</footer>

templates/navbar.html
<nav class="navbar navbar-expand-lg fixed-top">
  <div class="container">

      <a class="navbar-brand" href="{% url 'farms:home' %}">ZAMBOANGA FARMS</a>

      <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
          <span class="navbar-toggler-icon"></span>
      </button>

      <div class="collapse navbar-collapse" id="navbarNav">
          <ul class="navbar-nav ml-lg-auto">
              <li class="nav-item">
                  <a href="{% url 'farms:home' %}" class="nav-link smoothScroll">Home</a>
              </li>

              <li class="nav-item">
                  <a href="{% url 'farms:about' %}" class="nav-link smoothScroll">About</a>
              </li>

              <li class="nav-item">
                  <a href="#contact" class="nav-link smoothScroll">Contact</a>
              </li>

              <li class="nav-item">
                  <a href="{% url 'farms:services' %}" class="nav-link smoothScroll">Services</a>
              </li>

          </ul>
      </div>
  </div>
</nav>