farms/urls.py
from django.urls import path
from . import views 

app_name = "farms"

urlpatterns = [
    path('',views.HomeView.as_view(), name="home"),
    path('categories/',views.categories,name="categories"),
    path('crop/<slug:slug>/',views.detail, name="crop-detail"),
    path('about/',views.about_us,name="about"),
    path('services/',views.services,name="services"),
]

farms_database/urls.py
from django.contrib import admin
from django.urls import path, include

from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('farms.urls')),
]

# To display images
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

templates/store/about.html
{% extends 'base.html' %}
{% load static %}
{% block content %}
<section>
    <div class = "container">
       
    </div>
</section>
{% endblock content %}

templates/store/categories.html
{% extends 'base.html' %}
{% load static %}
{% block content %}
<div class = "container py-5">
    <section class = "py-5">
    <header>
      <p class="small text-muted small text-uppercase mb-1">Recommended Crops</p>
      <h2 class="h5 text-uppercase mb-4">Best crops for planting</h2>
    </header>
    <div class="row">
        {% if total_rain < total_dry %}
            {% for crop in crops_dry %}
            <div class="col-lg-3 col-md-4 col-6">
                <a href="{% url 'farms:crop-detail' crop.slug %}" class="d-block mb-4 h-100">
                    <img class="img-fluid img-thumbnail" src="{{ crop.crop_image.url }}" alt="{{g.description}}">
                </a>
              </div> 
            {% endfor %}
        {% else %}
        {% for crop in crops_rainy %}
            <div class="col-lg-3 col-md-4 col-6">
                <a href="{% url 'farms:crop-detail' crop.slug %}" class="d-block mb-4 h-100">
                    <img class="img-fluid img-thumbnail" src="{{ crop.crop_image.url }}" alt="{{g.description}}">
                </a>
              </div> 
            {% endfor %}
        {% endif %}
    </div>
    <hr>
    <header>
        <p class="small text-muted small text-uppercase mb-1">Made For You</p>
        <h2 class="h5 text-uppercase mb-4">List of crops</h2>
      </header>
      <div class="row">
              {% for crop in crops %}
              <div class="col-lg-3 col-md-4 col-6">
                  <a href="{% url 'farms:crop-detail' crop.slug %}" class="d-block mb-4 h-100">
                      <img class="img-fluid img-thumbnail" src="{{ crop.crop_image.url }}" alt="{{g.description}}">
                  </a>
                </div> 
              {% endfor %}
      </div>
    <p>Total number of sunny: {{total_dry}} </p>
    <p>Total number of rainy: {{total_rain}}</p>
</section>
</div>
{% endblock content %}

templates/store/detail.html
{% extends 'base.html' %}
{% load static %}
{% block content %}
<section class="py-5">
    <div class="container py-5">
      <div class="row mb-5">
        <div class="col-lg-6">
          <!-- PRODUCT SLIDER-->
          <div class="row m-sm-0">
            
            <div class="col-sm-12 order-1 order-sm-2">
              <div class="owl-carousel product-slider" data-slider-id="1">
                {% if crop.crop_image %}
                  <a class="d-block" href="{{crop.crop_image.url}}" data-lightbox="product" title="{{crop.title}}"><img class="img-fluid" src="{{crop.crop_image.url}}" alt="{{crop.title}}"></a>
                {% endif %}
              </div>
            </div>
          </div>
        </div>
        <!-- PRODUCT DETAILS-->
        <div class="col-lg-6">
          <h1>{{crop.title}}</h1>
          <p class="text-muted lead">Crop Description</p>
          <p class="text-small mb-4" align="justify">{{crop.crop_description }}</p>
          <ul class="list-unstyled small d-inline-block">
            <li class="px-3 py-2 mb-1 bg-white text-muted"><strong class="text-uppercase text-dark">Category:</strong><a class="reset-anchor ml-2" href="#">{{crop.category}}</a></li>
          </ul>
        </div>
      </div>
      <!-- DETAILS TABS-->
      <ul class="nav nav-tabs border-0" id="myTab" role="tablist">
        <li class="nav-item"><a class="nav-link active" id="preparation-tab" data-toggle="tab" href="#preparation" role="tab" aria-controls="preparation" aria-selected="true">Crop Preparation</a></li>
        <li class="nav-item"><a class="nav-link" id="planting-tab" data-toggle="tab" href="#planting" role="tab" aria-controls="planting" aria-selected="false">Crop Planting</a></li>
        <li class="nav-item"><a class="nav-link" id="manage-tab" data-toggle="tab" href="#manage" role="tab" aria-controls="manage" aria-selected="false">Pest & Disease Management</a></li>
        <li class="nav-item"><a class="nav-link" id="risk-tab" data-toggle="tab" href="#risk" role="tab" aria-controls="risk" aria-selected="false">Risk Assessment</a></li>
      </ul>
      <div class="tab-content mb-5" id="myTabContent">
        <div class="tab-pane fade show active" id="preparation" role="tabpanel" aria-labelledby="preparation-tab">
          <div class="p-4 p-lg-5 bg-white">
            <div class="card mb-4" id="forms">
              <div class="card-header">
                <small>
                Crop Preparation Section 
                </small>
              </div>
            <div class="card-body">
              <p class="text-muted text-small mb-0" align="justify">{{crop.crop_preparation|linebreaks}}</p>
            </div>
          </div>
          </div>
        </div>
        <div class="tab-pane fade" id="planting" role="tabpanel" aria-labelledby="planting-tab">
            <div class="p-4 p-lg-5 bg-white">
                <h6 class="text-uppercase">Crop Planting </h6>
                <p class="text-muted text-small mb-0" align="justify">{{crop.crop_planting|linebreaks}}</p>
            </div>
        </div>
        <div class="tab-pane fade" id="manage" role="tabpanel" aria-labelledby="manage-tab">
            <div class="p-4 p-lg-5 bg-white">
                <h6 class="text-uppercase">Pest & Disease Management</h6>
                <p class="text-muted text-small mb-0" align="justify">{{crop.crop_management|linebreaks}}</p>
            </div>
        </div>
        <div class="tab-pane fade" id="risk" role="tabpanel" aria-labelledby="risk-tab">
          <div class="p-4 p-lg-5 bg-white">
              <h6 class="text-uppercase">Risk Assessment</h6>
              <br>
              {% if total_rain < total_dry %}
              <table class="table table-bordered">
                <thead>
                  <tr>
                    <th scope="col">Risk Assessment Pest Dry Season</th>
                    <th scope="col">Control & Prevention</th>
                  </tr>
                </thead>
                <tbody>
                  <tr>
                    <th scope="row">{{crop.risk_dry_pest|linebreaks}}</th>
                    <th scope="row">{{crop.prevention_dry_pest|linebreaks}}</th>
                  </tr>
                </tbody>
              </table>
              <table class="table table-bordered">
                <thead>
                  <tr>
                    <th scope="col">Risk Assessment Disease  Dry Season</th>
                    <th scope="col">Control & Prevention</th>
                  </tr>
                </thead>
                <tbody>
                  <tr>
                    <th scope="row">{{crop.risk_dry_disease|linebreaks}}</th>
                    <th scope="row">{{crop.prevention_dry_disease|linebreaks}}</th>
                  </tr>
                </tbody>
              </table>
              {% else %}
              <table class="table table-bordered">
                <thead>
                  <tr>
                    <th scope="col">Risk Assessment Pest Rainy Season</th>
                    <th scope="col">Control & Prevention</th>
                  </tr>
                </thead>
                <tbody>
                  <tr>
                    <th scope="row">{{crop.risk_rainy_pest|linebreaks}}</th>
                    <th scope="row">{{crop.prevention_rainy_pest|linebreaks}}</th>
                  </tr>
                </tbody>
              </table>
              <table class="table table-bordered">
                <thead>
                  <tr>
                    <th scope="col">Risk Assessment Disease Rainy Season</th>
                    <th scope="col">Control & Prevention</th>
                  </tr>
                </thead>
                <tbody>
                  <tr>
                    <th scope="row">{{crop.risk_rainy_disease|linebreaks}}</th>
                    <th scope="row">{{crop.prevention_rainy_disease|linebreaks}}</th>
                  </tr>
                </tbody>
              </table>
              {% endif %}
      </div>
    </div>
  </section>
{% endblock content %}

templates/store/index.html
{% extends 'base.html' %}
{% load static %}
{% load crispy_forms_tags %}
{% block content %}
<section class="hero d-flex flex-column justify-content-center align-items-center" id="home">

    <div class="bg-overlay"></div>

    <div class="container">
        <div class="row">

            <div class="col-lg-8 col-md-10 mx-auto col-12">
                <div class="hero-text mt-5 text-center">

                    <!--<h6 data-aos="fade-up" data-aos-delay="300">new way to build a healthy lifestyle!</h6>-->

                    <h1 class="text-white" data-aos="fade-up" data-aos-delay="500">Crops exist in the weather and light rays that surround them.</h1>
                    <p class="text-white" data-aos="fade-up" data-aos-delay="500">Help's you manage your plants and encourages you to do gardening in your area.</p>
                    <a href="{% url 'farms:categories' %}" class="btn custom-btn bordered mt-3" data-aos="fade-up" data-aos-delay="700">Get Started</a>

                </div>
            </div>

        </div>
    </div>
</section>

<section class = "services-area bg-gray section-padding-100-0">
    <div class="container">
        <div class="row">
            <div class="col-12">
                <!-- Section Heading -->
                <div class="section-heading text-center">
                    <h2>OUR SERVICES</h2>
                    <p>We provide the steps to minimize the risk of crop planting!</p>
                </div>
            </div>
        </div>
        <div class="row justify-content-between" data-aos="fade-up" data-aos-delay="300">
            <div class="col-12 col-lg-5">
            <div class="single-service-area d-flex align-items-center">
                <!-- Icon -->
                <!-- Content -->
                <div class="service-content">
                    <h5>Crops Care</h5>
                    <p>All of your crops will be cared for in a methodical manner with the assistance of a certified agriculturist.</p>
                </div>
            </div>
            <div class="single-service-area d-flex align-items-center">
                <!-- Icon -->
                <!-- Content -->
                <div class="service-content">
                    <h5>Weather Monitoring</h5>
                    <p>We'll give you recommendations on the best crop to plant for the month based on real-time weather and flood level monitoring.</p>
                </div>
            </div>
            <div class="single-service-area d-flex align-items-center">
                <!-- Icon -->
                <!-- Content -->
                <div class="service-content">
                    <h5>Crop Planting &amp; Introduction</h5>
                                <p>We'll guide you through the process of planting crops, as well as introduce you to crop care and crop maintenance.</p>
                </div>
            </div>
            
        </div>
    </div>
    </div>
</section>
<section class="contact-area section-padding-100-0">
    <div class="container">
        <hr>
        <div class="row align-items-center justify-content-between">
            <div class="col-12 col-lg-5">
                <!-- Section Heading -->
                <div class="section-heading">
                    <h2>GET IN TOUCH</h2>
                    <p>Send us a message, we will call back later</p>
                </div>
                <!-- Contact Form Area -->
                <div class="contact-form-area mb-100">
                    <form method="post" action="">
                        <fieldset>
                          {% csrf_token %}
              
                          {% for fm in form %}
                              <div class="form-group">
                                  {{fm.label_tag}}
                                  {{fm}}
                                  <small class="text-danger">{{fm.errors|striptags}}</small>
                              </div>
                          {% endfor %}
                          <button class="btn btn-primary" type="submit">Submit</button>
                        </fieldset>
              
                        {% if form.non_field_errors %}
                          {% for error in non_field_errors %}
                              <p class="alert alert-danger my-3">
                                  {{error}}
                              </p>
                          {% endfor %}
                        {% endif %}
              
                      </form>
                      <br>
                </div>
            </div>
        </div>
    </div>
</section>
{% endblock content %}

templates/store/services.html
{% extends 'base.html' %}
{% load static %}
{% block content %}
<div class = "container py-5">
    <section class = "py-5">
      <p>30 Day Weather Forecast</p>
      <div class="row">
        <div class="col">
          <div class = "card mb-4">
            <div class = "card-header justify-content-center text-center">
              <p>{{format_date_1}}</p>
              <h5 class="mb-0 font-weight-bold text-center"> {{temperature}}&deg; C </h5>
              <span class="small grey text-uppercase">{{description}}</span>
            </div>
            <div class = "card-body">
              <p class="my-1">
                <i class="fa-solid fa-wind"></i>
               <span> {{speed}} m/s</span>
            </p>
            <p class="my-1"> 
              <i class="fa-solid fa-cloud"></i>
               <span> {{cloud}} %</span> 
            </p>
            </div>
          </div>
        </div>
        <div class='w-100 d-md-none'></div>
        <div class="col">
          <div class = "card mb-4">
            <div class = "card-header justify-content-center text-center">
              <p>{{format_date_2}}</p>
              <h5 class="mb-0 font-weight-bold text-center"> {{temperature_2}}&deg; C </h5>
              <span class="small grey text-uppercase">{{description_2}}</span>
            </div>
            <div class = "card-body">
              <p class="my-1">
                <i class="fa-solid fa-wind"></i>
               <span> {{speed_2}} m/s</span>
            </p>
            <p class="my-1"> 
              <i class="fa-solid fa-cloud"></i>
               <span> {{cloud_2}} %</span> 
            </p>
            </div>
          </div>
        </div>
        <div class='w-100 d-md-none'></div>
        <div class="col">
          <div class = "card mb-4">
            <div class = "card-header justify-content-center text-center">
              <p>{{format_date_3}}</p>
              <h5 class="mb-0 font-weight-bold text-center"> {{temperature_3}}&deg; C </h5>
              <span class="small grey text-uppercase">{{description_3}}</span>
            </div>
            <div class = "card-body">
              <p class="my-1">
                <i class="fa-solid fa-wind"></i>
               <span> {{speed_3}} m/s</span>
            </p>
            <p class="my-1"> 
              <i class="fa-solid fa-cloud"></i>
               <span> {{cloud_3}} %</span> 
            </p>
            </div>
          </div>
        </div>
        <div class='w-100 d-md-none'></div>
        <div class="col">
          <div class = "card mb-4">
            <div class = "card-header justify-content-center text-center">
              <p>{{format_date_4}}</p>
              <h5 class="mb-0 font-weight-bold text-center"> {{temperature_4}}&deg; C </h5>
              <span class="small grey text-uppercase">{{description_4}}</span>
            </div>
            <div class = "card-body">
              <p class="my-1">
                <i class="fa-solid fa-wind"></i>
               <span> {{speed_4}} m/s</span>
            </p>
            <p class="my-1"> 
              <i class="fa-solid fa-cloud"></i>
               <span> {{cloud_4}} %</span> 
            </p>
            </div>
          </div>
        </div>
        <div class='w-100 d-md-none'></div>
        <div class="col">
          <div class = "card mb-4">
            <div class = "card-header justify-content-center text-center">
              <p>{{format_date_5}}</p>
              <h5 class="mb-0 font-weight-bold text-center"> {{temperature_5}}&deg; C </h5>
              <span class="small grey text-uppercase">{{description_5}}</span>
            </div>
            <div class = "card-body">
              <p class="my-1">
                <i class="fa-solid fa-wind"></i>
               <span> {{speed_5}} m/s</span>
            </p>
            <p class="my-1"> 
              <i class="fa-solid fa-cloud"></i>
               <span> {{cloud_5}} %</span> 
            </p>
            </div>
          </div>
        </div>
        <div class='w-100 d-md-none'></div>
        <div class="col">
          <div class = "card mb-4">
            <div class = "card-header justify-content-center text-center">
              <p>{{format_date_6}}</p>
              <h5 class="mb-0 font-weight-bold text-center"> {{temperature_6}}&deg; C </h5>
              <span class="small grey text-uppercase">{{description_6}}</span>
            </div>
            <div class = "card-body">
              <p class="my-1">
                <i class="fa-solid fa-wind"></i>
               <span> {{speed_6}} m/s</span>
            </p>
            <p class="my-1"> 
              <i class="fa-solid fa-cloud"></i>
               <span> {{cloud_6}} %</span> 
            </p>
            </div>
          </div>
        </div>
        <div class='w-100 d-md-none'></div>
        <div class="col">
          <div class = "card mb-4">
            <div class = "card-header justify-content-center text-center">
              <p>{{format_date_7}}</p>
              <h5 class="mb-0 font-weight-bold text-center"> {{temperature_7}}&deg; C </h5>
              <span class="small grey text-uppercase">{{description_7}}</span>
            </div>
            <div class = "card-body">
              <p class="my-1">
                <i class="fa-solid fa-wind"></i>
               <span> {{speed_7}} m/s</span>
            </p>
            <p class="my-1"> 
              <i class="fa-solid fa-cloud"></i>
               <span> {{cloud_7}} %</span> 
            </p>
            </div>
          </div>
        </div>
        <div class='w-100 d-md-none'></div>
        <div class="col">
          <div class = "card mb-4">
            <div class = "card-header justify-content-center text-center">
              <p>{{format_date_8}}</p>
              <h5 class="mb-0 font-weight-bold text-center"> {{temperature_8}}&deg; C </h5>
              <span class="small grey text-uppercase">{{description_8}}</span>
            </div>
            <div class = "card-body">
              <p class="my-1">
                <i class="fa-solid fa-wind"></i>
               <span> {{speed_8}} m/s</span>
            </p>
            <p class="my-1"> 
              <i class="fa-solid fa-cloud"></i>
               <span> {{cloud_8}} %</span> 
            </p>
            </div>
          </div>
        </div>
        

      </div>
    </section>
  </div>
{% endblock content%}